#! /bin/sh

. /dni-gconfig

# DNI copyright (c) 2015
firewall4="/usr/sbin/net-wall"
firewall6="/usr/sbin/net-wall6"

conffile="/etc/net-wall/net-wall.conf"

usage()
{
	printf "%s\n" \
		"Usage:	firewall.sh start|stop|restart|boot|reload [ipv6|ipv4]" \
		"" \
		"option:" \
		"	ipv6	set ipv6 firewall rules." \
		"	ipv4	set ipv4 firewall rules." \
		"  if both ipv4 and ipv6 are all not supply, will use ipv4."
}

start()
{
	$firewall4 rule
	[ "x$1" = "xipv6" ] && $firewall6 start || $firewall4 start
}

stop()
{
	[ "x$1" = "xipv6" ] && $firewall6 stop || $firewall4 stop
}

restart()
{
	stop $@
	start $@
}

boot()
{
	config
	start $@
}

config()
{
	# TODO: generate config file.
	cat > $conffile <<-EOF
	### GENERATED BY firewall.sh AUTOMATICALLY, DON'T EDIT BY MANUAL ###
	
	sys_wan_ifname		"${DGC_WAN_BR_IF}"
	#sys_ppp_ifname		"ppp0"
	sys_lan_ifname		"${DGC_LAN_BR_IF}"
	#sys_6ppp_ifname	"ppp2"
	#sys_6to4_ifname	"sit1"
	#sys_6l2tp_ifname	"ppp3"
	#feature_spi_dos	TRUE
	#feature_ip_mac		TRUE
	#feature_pptp		TRUE
	#feature_multi_pppoe	TRUE
	#feature_dni_log	TRUE
	#feature_upnp		TRUE
	#feature_conenat	TRUE
	#feature_snatp2p	TRUE
	#feature_qos		TRUE
	#feature_qqos		TRUE
	#feature_blkurl		TRUE
	#feature_port_trig	TRUE
	#feature_dns_hjk	TRUE
	#feature_ntgr_rjct	TRUE
	#feature_ipv6_cone	TRUE
	#feature_portfw_eh	TRUE
	#feature_pppoe_ru2	TRUE
	#feature_ipp2p		FALSE
	#feature_filter		FALSE
	#feature_igmp		TRUE
	#feature_l2tp		TRUE
	#info_l2tp_port		1701
	#feature_nat_mg		FALSE
	#feature_raw_notrack	TRUE
	#feature_https		TRUE
	#feature_upnp_log	TRUE
	#feature_apmod		TRUE
	#feature_ipv6		TRUE
	EOF
}

reload()
{
	restart $@
}

case $1 in
	start|stop|restart|boot|reload)
		eval $@ ;;
	*)
		usage ;;
esac
