obj-m += lantiq_vrx320_vectoring.o
obj-m += lantiq_vrx320_vectoring_test.o

lantiq_vrx320_vectoring-objs := vrx320_vectoring.o vrx320_vectoring_stub.o
lantiq_vrx320_vectoring_test-objs := vrx320_vectoring_test.o
