# GENERATED AUTOMATICALLY BY configure, DON'T EDIT THIS FILE MANUALLY.

export INSTALL_DIR:=install -d -m0755
export INSTALL_BIN:=install -m0755
export INSTALL_DATA:=install -m0644
export INSTALL_CONF:=install -m0600
export LN:=ln -sf
export CP:=cp -fpR
export TOUCH:=touch

export INS_DIR_PRE:=
export INS_BIN_DIR:=$(INS_DIR_PRE)/sbin
export INS_USR_BIN_DIR:=$(INS_DIR_PRE)/usr/sbin

export NET_UTIL_CONF:=/home/roger.luo/d7800-stage2.git/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/net-util/files/net-util.config

SOURCE_DIR="src"
FILES_DIR="files"
SCRIPT_DIR="scripts"

all %::
	$(MAKE) -C $(SOURCE_DIR) $@
	$(MAKE) -C $(SCRIPT_DIR) $@
