#!/bin/sh

#
# Exection begins here
#
. /dni-gconfig

CONFIG="/bin/config"

TRAFFIC_MTD_PATH=$(part_path traffic)
TRAFFIC_STATUS=/tmp/traffic_meter/traffic_meter.conf

gen_config()
{
	wan_proto="$($CONFIG get wan_proto)"

	if [ "$wan_proto" = "pppoe" ] || [ "$wan_proto" = "pptp" ] ;then
		connection_type=0
	else
		connection_type=1
	fi

	if [ -f /tmp/traffic_meter/last_conn_time ] ;then
		last_conn_time=`cat /tmp/traffic_meter/last_conn_time | awk -F. '{print $1}'`
	else
		last_conn_time=0
	fi
	if [ -f /tmp/traffic_meter/last_stop_time ] ;then
		last_stop_time=`cat /tmp/traffic_meter/last_stop_time | awk -F. '{print $1}'`
	else
		last_stop_time=0
	fi

	# please keep "GUI_Region" in the last line.
	GUI_Region="$($CONFIG get GUI_Region)"
	if [ "$GUI_Region" != "German" ]; then
		region=0
	else
		region=1
	fi

	cat > $TRAFFIC_STATUS <<-EOF
		connection_type=$connection_type
		endis_traffic_meter=$($CONFIG get endis_traffic)
		control_type=$($CONFIG get ctrl_volumn_time)
		volume_control_type=$($CONFIG get limit)
		monthly_volume_limit=$($CONFIG get mon_volumn_limit)
		round_up_data=$($CONFIG get round_up)
		monthly_time_limit=$($CONFIG get mon_time_limit)
		restart_day=$($CONFIG get traffic_restart_day)
		restart_time_hour=$($CONFIG get restart_counter_time | awk -F: '{print $1}')
		restart_time_min=$($CONFIG get restart_counter_time | awk -F: '{print $2}')
		traffic_led=$($CONFIG get traffic_led)
		traffic_block=$($CONFIG get traffic_block_all)
		last_conn_time=$last_conn_time
		last_stop_time=$last_stop_time
		left_volume_time=$($CONFIG get left_time_volumn)
		GUI_Region=$region
	EOF
}
boot() {
	echo -n "traffic_meter boot : "
	mkdir -p /tmp/traffic_meter
	start
}

start() {
	echo -n "traffic_meter start : "
	cp -arf /usr/traffic_meter/ /tmp/
	gen_config
	pidof traffic_meter || traffic_meter -w $DGC_WAN_BR_IF -p $DGC_WAN_PPP_IF -m $TRAFFIC_MTD_PATH
	echo "."
}

stop() {
	echo -n "traffic_meter stop : "
	killall traffic_meter
	echo "."
}

config() {
	echo -n "traffic_meter config_update : "
	gen_config
	killall -USR1 traffic_meter
	##To fix the bug 25516 & 26430
	sleep 10
	$CONFIG set default_traffic="1"
	$CONFIG commit
	echo "."
}

reload() {
	echo -n "traffic_meter restart_counter : "
	killall -USR2 traffic_meter
	echo "."
}

case "$1" in
boot)
	boot
	;;

start)
	start
	;;

stop)
	stop
	;;

restart)
	stop
	start
	;;
config|config_update)
	config
	;;
reload|restart_counter)
	reload
	;;
*)
	echo "Usage: ${0##*/} {boot|start|stop|restart|config|config_update|reload|restart_counter}"
	exit 1
	;;
esac

