#!/bin/sh /etc/rc.common
START=19
. /lib/cfgmgr/cfgmgr.sh
. /lib/cfgmgr/enet.sh

detect_wan_port_status()
{
	if [ "x$(detcable show | grep "WAN  : Plug off")" != "x" ]; then
		echo -n 0 > /tmp/port_status
	else
		echo -n 1 > /tmp/port_status
		if [ "x$DSL_SUPPORT" = "x1" ]; then
			# DSL_SUPPORT=1 means support DSL.
			# dsl_wan_preference=1 means in DSL WAN mode.
			# dsl_wan_preference=2 means in Ethernet WAN mode.
			# We just need control Ethernet WAN mode LED here.
			[ "x$(config get dsl_wan_preference)" = "x2" ] && ledcontrol -n wan -c amber -s on
		else
			ledcontrol -n wan -c amber -s on
		fi
	fi
}

boot()
{
	et_init
	detect_wan_port_status
	/etc/init.d/qca-nss-ecm start
}

