#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=97

start() {
	[ -c /dev/watchdog ] || return 1
	[ -x $(which watchdog) ] || return 1
	service_start watchdog -t 5 /dev/watchdog
}
stop() {
	service_stop watchdog
}
